version: "3.7"

volumes:
  unit-test-training-db-data:

services:
  unit-test-training-db:
    image: postgres:14-alpine
    restart: always
    command: postgres
    volumes:
      - unit-test-training-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  unit-test-training-greenmail-server:
    image: greenmail/standalone:2.0.0
    ports:
      - "3025:3025"
      - "3110:3110"
      - "3143:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995"
      - "8280:8080"